import { User } from '../../../pages/Admin/UserManagment'
export const mockUsers: User[] = [
  {
    id: 'USR7823645912',
    name: 'Alex Knight',
    email: 'alex.knight@example.com',
    rating: 1850,
    gamesPlayed: 347,
    premium: true,
    createdAt: '2022-03-15T10:30:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    streaks: 12,
    rewards: 15,
    achievements: ['Grand Master', 'Tournament Winner', '100 Game Streak'],
    savedGames: 24,
    reports: 0,
  },
  {
    id: 'USR1293847560',
    name: 'Emma Bishop',
    email: 'emma.bishop@example.com',
    rating: 1720,
    gamesPlayed: 215,
    premium: true,
    createdAt: '2022-05-22T14:45:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    streaks: 7,
    rewards: 9,
    achievements: ['Quick Thinker', 'Defensive Expert'],
    savedGames: 18,
    reports: 1,
  },
  {
    id: 'USR4567890123',
    name: 'James Rodriguez',
    email: 'james.r@example.com',
    rating: 1950,
    gamesPlayed: 489,
    premium: true,
    createdAt: '2021-11-08T09:15:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    streaks: 30,
    rewards: 27,
    achievements: [
      'Grandmaster',
      'Undefeated Champion',
      'Strategy Expert',
      'Tournament Winner',
    ],
    savedGames: 56,
    reports: 0,
  },
  {
    id: 'USR7891234560',
    name: 'Olivia Chen',
    email: 'olivia.chen@example.com',
    rating: 1680,
    gamesPlayed: 178,
    premium: false,
    createdAt: '2022-07-30T16:20:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
    streaks: 5,
    rewards: 7,
    achievements: ['Rising Star'],
    savedGames: 12,
    reports: 0,
  },
  {
    id: 'USR2345678901',
    name: 'Michael Thompson',
    email: 'm.thompson@example.com',
    rating: 1530,
    gamesPlayed: 132,
    premium: false,
    createdAt: '2022-09-12T11:10:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/men/42.jpg',
    streaks: 3,
    rewards: 4,
    achievements: [],
    savedGames: 8,
    reports: 2,
  },
  {
    id: 'USR8901234567',
    name: 'Sophia Williams',
    email: 'sophia.w@example.com',
    rating: 1890,
    gamesPlayed: 412,
    premium: true,
    createdAt: '2021-12-05T08:30:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    streaks: 22,
    rewards: 19,
    achievements: ['Tactical Genius', 'Blitz Champion', '500 Games Club'],
    savedGames: 37,
    reports: 1,
  },
  {
    id: 'USR3456789012',
    name: 'Daniel Lee',
    email: 'daniel.lee@example.com',
    rating: 1420,
    gamesPlayed: 87,
    premium: false,
    createdAt: '2023-01-18T15:40:00Z',
    banned: true,
    avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
    streaks: 0,
    rewards: 2,
    achievements: [],
    savedGames: 5,
    reports: 7,
  },
  {
    id: 'USR9012345678',
    name: 'Isabella Garcia',
    email: 'isabella.g@example.com',
    rating: 1750,
    gamesPlayed: 256,
    premium: false,
    createdAt: '2022-04-09T12:50:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    streaks: 9,
    rewards: 11,
    achievements: ['Comeback Queen', 'Endgame Expert'],
    savedGames: 19,
    reports: 0,
  },
  {
    id: 'USR5678901234',
    name: 'William Brown',
    email: 'w.brown@example.com',
    rating: 1610,
    gamesPlayed: 201,
    premium: false,
    createdAt: '2022-06-27T13:15:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/men/81.jpg',
    streaks: 4,
    rewards: 8,
    achievements: ['Opening Master'],
    savedGames: 15,
    reports: 1,
  },
  {
    id: 'USR0123456789',
    name: 'Charlotte Taylor',
    email: 'charlotte.t@example.com',
    rating: 1580,
    gamesPlayed: 167,
    premium: true,
    createdAt: '2022-08-14T10:05:00Z',
    banned: false,
    avatar: 'https://randomuser.me/api/portraits/women/57.jpg',
    streaks: 6,
    rewards: 6,
    achievements: ['Puzzle Solver'],
    savedGames: 11,
    reports: 0,
  },
]
